### ISSUE TITLE
main branch protection

### ISSUE THREAD

**Issue by TheCollinsByte** [zoxabbasi/split-landing_brad-traversy#3]
I would suggest to protect the main branch as the repository owner. For perfect work flow to separate the `PROD Branch` from the features branch for a perfect workflow

**Comment by zoxabbasi** [comment]
I'm new to this world and was confused tbh but I manged to create a branch
Appreciate your suggestion.

**Comment by TheCollinsByte** [comment]
I would like to contribute more from the projects

**Comment by TheCollinsByte** [comment]
What is the next project?? I would like to contribute more and more

**Comment by TheCollinsByte** [comment]
> I'm new to this world and was confused tbh but I manged to create a branch Appreciate your suggestion.

Welcome to the world.

**Comment by zoxabbasi** [comment]
I don't know how this 'pull thing' works exactly.
I'm trying to get my head around it at the moment lol

**Comment by zoxabbasi** [comment]
> What is the next project?? I would like to contribute more and more

I will update you once something comes up.

**Comment by zoxabbasi** [comment]
> What is the next project?? I would like to contribute more and more

https://github.com/zoxabbasi/sound-board_brad-traversy/blob/main/js/app.js

You wished for something, I have been facing an issue here. I want the sound to stop if the next button is clicked, but the stopsong() doesn't work.

**Comment by TheCollinsByte** [comment]
> https://github.com/zoxabbasi/sound-board_brad-traversy/blob/main/js/app.js
> 
> You wished for something, I have been facing an issue here. I want the sound to stop if the next button is clicked, but the stopsong() doesn't work.

I will check on it. Worry out
